# Generated by Django 4.1.5 on 2023-02-26 14:54

import annoying.fields
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mmorgnews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="user",
            field=annoying.fields.AutoOneToOneField(
                default=False,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="user",
            field=annoying.fields.AutoOneToOneField(
                default=False,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
