# Generated by Django 4.1.5 on 2023-02-26 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mmorgnews", "0004_alter_author_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mmorgnews.users",
                unique=True,
            ),
        ),
    ]
