# Generated by Django 4.1.5 on 2023-02-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mmorgnews", "0006_remove_author_user_author_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="author",
            field=models.CharField(default="", max_length=150, unique=True),
        ),
    ]
