# Generated by Django 4.1.5 on 2023-03-05 19:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("height", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("data", models.ImageField(max_length=4000, upload_to="uploads/")),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("fam", models.CharField(max_length=150)),
                ("name", models.CharField(max_length=150)),
                ("otc", models.CharField(max_length=150)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=14,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 12 digits allowed.",
                                regex="^\\+?1?\\d{9,12}$",
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PerevalAdded",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("beauty_title", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("other_titles", models.CharField(max_length=255)),
                ("add_time", models.DateTimeField(auto_now_add=True)),
                ("winter", models.CharField(max_length=100)),
                ("summer", models.CharField(max_length=100)),
                ("autumn", models.CharField(max_length=100)),
                ("spring", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "new"),
                            ("pending", "pending"),
                            ("accepted", "accepted"),
                            ("rejected", "rejected"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "coords",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="spr1.coords"
                    ),
                ),
                (
                    "images",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="spr1.image"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="spr1.users"
                    ),
                ),
            ],
        ),
    ]
