# Generated by Django 4.1.5 on 2023-03-08 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("spr1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="perevaladded",
            name="connect",
            field=models.CharField(default=" ", max_length=1),
        ),
        migrations.AlterField(
            model_name="perevaladded",
            name="coords",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="spr1.coords"
            ),
        ),
    ]
