# Generated by Django 4.1.5 on 2023-03-12 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("spr1", "0002_perevaladded_connect_alter_perevaladded_coords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perevaladded",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="spr1.users",
            ),
        ),
    ]
