# Generated by Django 4.1.5 on 2023-03-14 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("spr1", "0003_alter_perevaladded_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perevaladded",
            name="coords",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coords",
                to="spr1.coords",
            ),
        ),
        migrations.AlterField(
            model_name="perevaladded",
            name="images",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="spr1.image",
            ),
        ),
    ]
