# Generated by Django 4.1.5 on 2023-01-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("D5", "0004_alter_category_name_category_mymodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_category_en",
            field=models.CharField(
                help_text="category name", max_length=255, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="name_category_ru",
            field=models.CharField(
                help_text="category name", max_length=255, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="mymodel",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mymodel",
            name="name_ru",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
